### ISSUE TITLE
IWR6843ISK Raw_Data

### ISSUE THREAD

**Issue by PoderLEE** [JUSTWILLPOWER/TwoStage_sliding_processing#1]
你好我想詢問，您是透過甚麼方式讀取到它的原始數據?方便能提供資訊給我嗎?

**Comment by JUSTWILLPOWER** [comment]
你好，可以参考[iwr6843isk-HARbag](https://github.com/JUSTWILLPOWER/iwr6843isk-HARbag.git),你需要搭建ROS环境，以便使用iwr6843isk进行数据采集和处理.

**Comment by PoderLEE** [comment]
好的，我先試著了解，有問題我再請教你，謝謝!
